name: Build iSH App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Alpine tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc musl-dev  # Tools for compiling C code
      - name: Compile code
        run: gcc -o hello hello.c  # Compile a C file (replace with yours)
